services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /schema.yml
    network_mode: host
    ports:
      - 8888:8080
    volumes:
      - ./schema.yml:/schema.yml