version: '1.0'
services:
  db:
    image: postgres:17.3
    env_file:
      - ./haru_cafe_django/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./haru_cafe_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - type: bind
        source: ./haru_cafe_django
        target: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./haru_cafe_django/.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  frontend:
    build: ./angular
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
      - type: bind
        source: ./angular
        target: /app
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
