export enum Category {
  Juice = "Fresh Juice",
  Drink = "Drink",
  Food = "Food",
  SingleFlavor = "Single Flavor",
  MixedFlavor = "Mixed Flavor",
  Sandwich = "Sandwich",
  MiniPizza = "Mini Pizza",
  Bakery = "Bakery",
  Snack = "Snack",
  Coffee = "Coffee",
  HotCoffee = "Hot Coffee",
  IcedCoffee = "Iced Coffee",
  HotNonCoffee = "Hot Non-Coffee",
  IcedNonCoffee = "Iced Non-Coffee",
  Ade = "Ade",
  Seasonal = "Seasonal",
  HotTea = "Hot Tea",
}
